apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
    # projectId: ticketing-474615
  artifacts:
    # - image: asia.gcr.io/ticketing-474615/auth
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: asia.gcr.io/ticketing-474615/client
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    # - image: asia.gcr.io/ticketing-474615/tickets
    - image: tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    # - image: asia.gcr.io/ticketing-474615/orders
    - image: orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .